#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : testdisk
Version  : 7.1.wip
Release  : 1
URL      : https://www.cgsecurity.org/testdisk-7.1-WIP.tar.bz2
Source0  : https://www.cgsecurity.org/testdisk-7.1-WIP.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: testdisk-bin = %{version}-%{release}
Requires: testdisk-data = %{version}-%{release}
Requires: testdisk-license = %{version}-%{release}
Requires: testdisk-man = %{version}-%{release}
BuildRequires : libjpeg-turbo-dev
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(zlib)
BuildRequires : qtbase-dev
BuildRequires : qttools-dev
BuildRequires : util-linux-dev

%description
The GNOME icon theme is licensed under the GPL.
http://art.gnome.org/

%package bin
Summary: bin components for the testdisk package.
Group: Binaries
Requires: testdisk-data = %{version}-%{release}
Requires: testdisk-license = %{version}-%{release}

%description bin
bin components for the testdisk package.


%package data
Summary: data components for the testdisk package.
Group: Data

%description data
data components for the testdisk package.


%package doc
Summary: doc components for the testdisk package.
Group: Documentation
Requires: testdisk-man = %{version}-%{release}

%description doc
doc components for the testdisk package.


%package license
Summary: license components for the testdisk package.
Group: Default

%description license
license components for the testdisk package.


%package man
Summary: man components for the testdisk package.
Group: Default

%description man
man components for the testdisk package.


%prep
%setup -q -n testdisk-7.1-WIP

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558637643
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1558637643
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/testdisk
cp COPYING %{buildroot}/usr/share/package-licenses/testdisk/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fidentify
/usr/bin/photorec
/usr/bin/qphotorec
/usr/bin/testdisk

%files data
%defattr(-,root,root,-)
/usr/share/applications/qphotorec.desktop
/usr/share/icons/hicolor/48x48/apps/qphotorec.png
/usr/share/icons/hicolor/scalable/apps/qphotorec.svg

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/testdisk/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/testdisk/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/fidentify.8
/usr/share/man/man8/photorec.8
/usr/share/man/man8/qphotorec.8
/usr/share/man/man8/testdisk.8
/usr/share/man/zh_CN/man8/fidentify.8
/usr/share/man/zh_CN/man8/photorec.8
/usr/share/man/zh_CN/man8/qphotorec.8
/usr/share/man/zh_CN/man8/testdisk.8
